name = "filesystem-chat"
version = "0.1.0"
description = "Chat interface with filesystem access"
component_path = "/Users/colinrozzi/work/actors/filesystem-chat/target/wasm32-unknown-unknown/release/filesystem_chat.wasm"
init_data = "/Users/colinrozzi/work/actors/filesystem-chat/assets/init.json"

[interface]
implements = "ntwk:theater/actor"
requires = []

[[handlers]]
type = "runtime"
config = {}

[[handlers]]
type = "http-client"
config = {}

[[handlers]]
type = "http-server"
config = { port = 8080 }

[[handlers]]
type = "websocket-server"
config = { port = 8081 }

[[handlers]]
type = "filesystem"
config = { path = "/Users/colinrozzi/work/actors/filesystem-chat/assets" }
