name = "filesystem-chat"
version = "0.1.0"
description = "Chat interface with filesystem access"

[interface]
implements = "ntwk:theater/actor"
requires = []

[[handlers]]
type = "http-server"
config = { port = 8080 }

[[handlers]]
type = "websocket-server"
config = { port = 8081 }

[[handlers]]
type = "message-server"
config = { port = 8082 }
interface = "ntwk:theater/message-server-client"